apiVersion: v1
kind: Service
metadata:
  name: server-pod-orderservice
  labels:
    name: server-pod-orderservice
    app: cluster-1

spec:
  type: LoadBalancer
  ports:
    - port: 8070
      targetPort: 5000
  selector:
    name: server-pod-orderservice
    app: cluster-1
